POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhdHRpIiwiaWQiOiI1ZjNlMzFjMzIzNTVjZTEyNzAzZDY1YmIiLCJpYXQiOjE1OTc5MjQ4NzR9.5yVK8Vxz2lAVU05fo-gDXCyU4tmvgshc9TSbovCLY4U

{
    "title": "pallenseitsemäsblogi",
    "url": "https://localhost.com"
    //"userId": "5f3e31c32355ce12703d65bb"

}
